### PR TITLE
Configuration management

### PR DESCRIPTION
**Pull request by danlamanna**
@kotfic Work in progress, though it does work. No includes yet. Criticize.

### CODE REVIEW

**Comment by kotfic** [comment]
can we put `config_files`,  `get_config` and `get_pg_db` into a configuration class?  that way `get_pg_db` doesn't have to instantiate the config object and we only read the file(s) once?

Also maybe add some error checking for  `KeyError` in `get_pg_db`?  

Also how would you like to handle tests?

**Comment by danlamanna** [comment]
I want to add tests at the right time, meaning after I think we have somewhat solidified how things are going to work. I just don't want to write tests for infrastructure that might change drastically - this class might be safe, we'll talk about it.

Should we have a set of defaults we completely bork on if they aren't present in the default configuration? 

Should `config` be an `@property` with the `load` method?

**Comment by kotfic** [comment]
test strategy sounds good to me.   lets worry about defaults later,  i wouldn't worry about lazy loading -  probably config should be instantiated somewhere early in **init** or **main** or whatever and just imported from the module where its needed.  Does that sound right?

Otherwise LGTM

**Comment by danlamanna** [comment]
@kotfic Take a look at this and #9

**Pull request merged**
